### PR TITLE
Deploy production 22/12/2022

### PR DESCRIPTION
**Pull request by bombnp**
## Changes
- [x] #422 @bombnp 
- [x] #429 @saenyakorn 
- [x] #428 @Leomotors 
- [x] #415 @Leomotors @Nacnano 
- [x] #441 @Leomotors 
- [x] #444 @saenyakorn @Leomotors 
- [x] #446 @saenyakorn 
- [x] #451 @bombnp 
- [x] #449 @tithanayut 

Please approve these changes for prod.

We really should make prod deployment more agile and frequent lol

### CODE REVIEW

**Review by Leomotors — APPROVED** [review]

**Comment by Leomotors** [comment]
Should we use normal merge commit when merging to production branch?

**Comment by saenyakorn** [comment]
I would prefer `merge commit` when merging to Production. To preserve commit history.

**Review by saenyakorn — APPROVED** [review]

**Comment by bombnp** [comment]
That's true, I guess i'll leave merge commit options open. Just remember to squash and merge for normal PRs

**Comment by Leomotors** [comment]
@bombnp You can set the specific branch in protected branch to require linear history and everyone can only use squash merge.

**Comment by bombnp** [comment]
> @bombnp You can set the specific branch in protected branch to require linear history and everyone can only use squash merge.

ohh that is true! ty

**Pull request merged**
