### PR TITLE
Feat/scraper migration

### LINKED ISSUE #463: [BACKLOG] Migrate thinc-org/cugetreg-scraper to this repo
### Problem

Our scraper code is located in [thinc-org/cugetreg-scraper](https://github.com/thinc-org/cugetreg-scraper). We should move it here for obvious reasons.

### Task Description

Migrate [thinc-org/cugetreg-scraper](https://github.com/thinc-org/cugetreg-scraper) to this repo as another app.

### Additional Context

This might conflict with #456 so either do this task quickly before Turbo migration or do it after.

### Related Teams

- [ ] Frontend
- [X] Backend
- [ ] Data
- [ ] Design
- [ ] Infra
- [ ] QA

### Task Advisors

@bombnp

### PR DESCRIPTION
**Pull request by bombnp**
## Why did you create this PR
- Fixes #463 

## What did you do
- Created a new app `reg-scraper`
- Fix scraper's Dockerfile and Typescript problems (newer TS version in this monorepo broke the code)
- Tidy up some api Dockerfile typos
- Use winston logger (similar to `api` in #461)

Scraper app should work successfully when run `nx serve reg-scraper` and it successfully builds docker images.

## Demo

[https://dev.cugetreg.com](https://dev.cugetreg.com)

## Checklist

- [ ] Deploy a demo
- [ ] Check browsers compatibility
- [ ] Wrote coverage tests

### CODE REVIEW

**Review by salaryhero-saenyakorn — COMMENTED** [review]
In my opinion, we should name this service as `cu-scraper` (or other prefix). Since, we may have a new service that scrape the data from other sources or even university.

**Comment by saenyakorn** [comment]
In my opinion, we should name this service as `cu-scraper` (or other prefix). Since, we may have a new service that scrape the data from other sources or even other universities data.

**Comment by bombnp** [comment]
> In my opinion, we should name this service as `cu-scraper` (or other prefix). Since, we may have a new service that scrape the data from other sources or even other universities data.

how about `regchula-scraper`, in this monorepo and docker image and k8s object

**Comment by saenyakorn** [comment]
Fine, i guess

**Comment by bombnp** [comment]
@saenyakorn pls review again

**Review by saenyakorn — APPROVED** [review]

**Pull request merged**
