### PR TITLE
Course Unit Test

### PR DESCRIPTION
**Pull request by samithiwat**
## Why did you create this PR

- because backend coverage is too low

## What did you do

- Create some unit test to improve the code coverage

## Demo

[https://dev.cugetreg.com](https://dev.cugetreg.com)

## Checklist

- [ ] Deploy a demo
- [ ] Check browsers compatibility
- [ ] Wrote coverage tests

### CODE REVIEW

**Comment by bombnp** [comment]
big praise 🙏🙏🙏🙏

**Comment by bombnp** [comment]
@samithiwat u wanna close this? lol

**Comment by samithiwat** [comment]
> @samithiwat u wanna close this? lol
wew lul
ตอนนี้เหลือแค่ test filter search ที่ยังไม่ได้ทำอ่ะ

**Comment by samithiwat** [comment]
ปิดเลยก็ได้ฮะเพราะ search น่าจะย้ายไปอีก service อยู่แล้ว

**Pull request closed without merging**
