### PR TITLE
feat: node 18

### PR DESCRIPTION
**Pull request by Leomotors**
test

### CODE REVIEW

**Comment by bombnp** [comment]
the last time we upgraded node resulted in a post-mortem lol.

hopefully this time it goes better

**Comment by saenyakorn** [comment]
Did you try running built apps in local? Did I work?

**Comment by saenyakorn** [comment]
If works, go merge!

**Comment by bombnp** [comment]
why does this bump `@cgr/codegen` and other lib packages tho? (also `admin-api` and `admin-web` which isn't being deployed yet). I think it should bump `api`, `web`, and `reg-scraper` only.

**Comment by Leomotors** [comment]
> Did you try running built apps (Docker) in local? Did I work?

test on production 😅

**Comment by Leomotors** [comment]
> why does this bump `@cgr/codegen` and other lib packages tho? (also `admin-api` and `admin-web` which isn't being deployed yet). I think it should bump `api`, `web`, and `reg-scraper` only.

I agree, let's fix that

**Comment by saenyakorn** [comment]
at least, merge this into dev first. We'll check if this works properly

**Comment by bombnp** [comment]
@Leomotors is this waiting for anything?

**Comment by Leomotors** [comment]
> @Leomotors is this waiting for anything?

Will continue on this when I have time

**Pull request closed without merging**
