### PR TITLE
Set recommendation link cursor to pointer / Revise course page layout

### PR DESCRIPTION
**Pull request by tithanayut**
## Why did you create this PR

- Currently, recommendation links show `text` cursor on hover which is unintuitive as it is clickable. The `pointer` cursor should be used instead.

image

## What did you do

- This PR sets recommendation links cursor to pointer

## Demo

[https://dev.cugetreg.com](https://dev.cugetreg.com)

## Checklist

- [x] Deploy a demo
- [x] Check browsers compatibility
- [ ] Wrote coverage tests (not applicable)

### CODE REVIEW

**Review by bombnp — APPROVED** [review]
not gonna lie, i had no idea this was not a pointer.

**Review by saenyakorn — APPROVED** [review]
LGTM

**Comment by saenyakorn** [comment]
Wait

**Comment by saenyakorn** [comment]
Something weird here? Why there is an extra space between search bar and recommended item

Screenshot 2566-01-25 at 20 41 35

Can you fix this too?

Found on `dev` environment

**Comment by tithanayut** [comment]
There is a component dedicated to creating that space when there are no filter tags. Do you seem to know what is the purpose of that? Or should I just remove it?

https://github.com/thinc-org/cugetreg/blob/14ea696cfdf197984a253f5f12c0f121140026bd/apps/web/src/modules/CourseSearch/components/TagList/index.tsx#L64-L70

**Comment by tithanayut** [comment]
This was introduced in https://github.com/thinc-org/cugetreg/commit/711832982904830820f453836f9dcff5de369e53 for a purpose. I am not sure how it reduces sticky search bar height though. Should I remove it or this it is for some specific cases? @suphon-t

**Comment by saenyakorn** [comment]
> There is a component dedicated to creating that space when there are no filter tags. Do you seem to know what is the purpose of that? Or should I just remove it?
> 
> https://github.com/thinc-org/cugetreg/blob/14ea696cfdf197984a253f5f12c0f121140026bd/apps/web/src/modules/CourseSearch/components/TagList/index.tsx#L64-L70

Not sure about this, but expected behavior is hiding (or removing) this empty block when there is no `tags`. Feel free to fix the code as you want.

**Comment by tithanayut** [comment]
I have removed the component that inserts the extra space. The dev environment doesn't seem to work right now though.

**Comment by saenyakorn** [comment]
Dev deployed. There's minor broken UI when scrolling. In red rectangle in the image, there's missing the top border line. It would be great if you help us fix this issue. Thanks in advance

Screenshot 2566-01-25 at 21 36 16

**Comment by bombnp** [comment]
@tithanayut you can deploy dev yourself btw, since you have infra access
1. Push to dev branch, go to action, get the image SHA digest
2. Go to repo [thinc-org/cugetreg-gitops](https://github.com/thinc-org/cugetreg-gitops), go to `web/overlay/dev/kustomization.yaml`, change the image SHA, then push to master
3. Go to argo.internal.cugetreg.com, refresh and sync the `cugetreg-web` application.

we haven't fixed the CI/CD yet sadly

**Comment by bombnp** [comment]
i've deployed it for u for now

**Review by suphon-t — APPROVED** [review]

**Pull request merged**
