### PR TITLE
[Feature] Add E2E Test for web

### PR DESCRIPTION
**Pull request by saenyakorn**
## Why did you create this PR

- Because E2E tests are need for enterprise application including CU Get Reg

## What did you do

- Initialize E2E tests project using Playwright
- Add workflow_dispatch for e2e tests

## Demo

[https://dev.cugetreg.com](https://dev.cugetreg.com)

## Checklist

- [ ] Deploy a demo
- [ ] Check browsers compatibility
- [ ] Wrote coverage tests

### CODE REVIEW

**Comment by bombnp** [comment]
Is this doing any testing for our app right now? Looks a like a template for future tests only.

**Comment by saenyakorn** [comment]
Just the template. Not tests that related to CGR

**Review by bombnp — APPROVED** [review]
It's ok for now. Maybe add some basic tests to make it a real example for CGR?

**Comment by saenyakorn** [comment]
Will do next PR

**Pull request merged**
